### ISSUE TITLE
大佬，还会更新吗？我按照教程做的一直报错。

### ISSUE THREAD

**Issue by DanielGao97** [Neulana/vlight#2]
$ travis_setup_go
go version go1.12.1 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.12.1.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version go1.12.1 linux/amd64
go.env
$ go env
install
8.39s$ travis_install_go_dependencies 1.12.1 -v
3.22s$ go run main.go
panic: runtime error: index out of range
goroutine 1 [running]:
main.FetchFund(0xc000012c80, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/DanielGao97/vlight/main.go:75 +0x8b2
main.main()
	/home/travis/gopath/src/github.com/DanielGao97/vlight/main.go:220 +0x45
exit status 2
The command "go run main.go" exited with 1.
Done. Your build exited with 1.

**Comment by pinple** [comment]
你没有设置基金代码，需要添加环境变量`WATCH_FUND_CODE`，设置为你需要关注的基金的代码，多只基金就用竖线“|”分隔
